#!/usr/bin/env bash

VERSION="$1"

VERSION="$1"
VALID="^[0-9]\.$"

if [[ $VERSION =~ $VALID  ]]
then
  echo 'Enter only a valid version number of form 1.10 or 1.10.2'
  exit 1
fi

SERVER_FILE=minecraft_server.$VERSION.jar
SERVER_URL=https://s3.amazonaws.com/Minecraft.Download/versions/$VERSION/minecraft_server.$VERSION.jar
SOURCEPATH="/"

if [ -d "/vagrant" ] ; then
  SOURCEPATH="/vagrant/"
fi

java -version > /dev/null 2>&1
if [ $? -eq 0 ] ; then
  echo "Java already installed, moving on"
else
  sudo apt-get update
  sudo apt-get -y install openjdk-8-jre
fi

ls /opt/minecraft > /dev/null 2>&1

if [ $? -eq 0 ] ; then
  echo "Directory /opt/minecraft already exists, moving on"
else
  sudo mkdir /opt/minecraft
fi

cd /opt/minecraft

ls "$SERVER_FILE" > /dev/null 2>&1
if [ $? -eq 0 ] ; then
  echo "Minecraft server jar already in place, moving on"
else
  sudo wget $SERVER_URL
  sudo java -Xmx1024M -Xms1024M -jar minecraft_server.$VERSION.jar nogui
fi

sudo sed -i s/eula=false/eula=true/ eula.txt | sudo tee eula.txt --append
sudo cp "$SOURCEPATH"json/whitelist.json /opt/minecraft/whitelist.json
sudo java -Xmx1024M -Xms1024M -jar minecraft_server.$VERSION.jar nogui
