#!/usr/bin/env bash

VERSION="$1"
VALID="^[0-9]\.$"

if [[ $VERSION =~ $VALID  ]]
then
  echo 'Enter only a valid version number of form 1.10 or 1.10.2'
  exit 1
fi

DIR="$(dirname "$(which "$0")")"
SERVICE_DEFINITION="$(cat $DIR/service_template.txt)"

cd /opt/minecraft
sudo stop minecraft-server

sudo wget "https://s3.amazonaws.com/Minecraft.Download/versions/$VERSION/minecraft_server.$VERSION.jar" && \
sudo /etc/init/minecraft-server.conf < "${SERVICE_DEFINITION/__VERSION__/$VERSION}"

sudo start minecraft-server
